import enum


class AddImprovementKeys():
    BTN_SAVE_IMPROVEMENT = "-BTN_SAVE_IMPROVEMENT-"
    BTN_CANCEL_ADD_IMPROVEMENT = "-BTN_CANCEL_ADD_IMPROVEMENT-"

    COMBO_ASSEMBLY_STEP = "-COMBO_ASSEMBLY_STEP-"
    INPUT_IMPROVEMENT_TITLE = "-INPUT_IMPROVEMENT_TITLE-"
    MULTI_LINE_DESCRIPTION = "-MULTI_LINE_DESCRIPTION-"
    LISTBOX_FAILURES = "-LISTBOX_FAILURES-"

