import enum


class AddFailureKeys():
    BTN_SAVE_FAILURE = "-BTN_SAVE_FAILURE-"
    BTN_CANCEL_ADD_FAILURE = "-BTN_CANCEL_ADD_FAILURE-"

    COMBO_ASSEMBLY_STEP = "-COMBO_ASSEMBLY_STEP-"
    MULTI_LINE_DESCRIPTION = "-MULTI_LINE_DESCRIPTION-"
    LISTBOX_IMPROVEMENTS = "-LISTBOX_IMPROVEMENTS-"

