"""testing

Revision ID: 128920805ec5
Revises: d1556a538201
Create Date: 2022-08-25 15:49:02.201988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128920805ec5'
down_revision = 'd1556a538201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failuretype', sa.Column('failure_classification', sa.Enum('failure_type_overcurrent', 'failure_type_others', name='failureclassification'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failuretype', 'failure_classification')
    # ### end Alembic commands ###
