""".

Revision ID: 2239856f6d4a
Revises: aed0d4505863
Create Date: 2022-08-22 14:34:04.336455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2239856f6d4a'
down_revision = 'aed0d4505863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('title', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
