"""Failure Types

Revision ID: 3c5dc4b0972d
Revises: 44cc610aafff
Create Date: 2022-08-21 16:57:52.275153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5dc4b0972d'
down_revision = '44cc610aafff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correctiveaction',
    sa.Column('corrective_action_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('corrective_action_id')
    )
    op.create_table('failuretype',
    sa.Column('failuretype_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.PrimaryKeyConstraint('failuretype_id')
    )
    op.create_table('failure',
    sa.Column('failure_id', sa.Integer(), nullable=False),
    sa.Column('failure_type', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failure_type'], ['failuretype.failuretype_id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.transmission_id'], ),
    sa.PrimaryKeyConstraint('failure_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure')
    op.drop_table('failuretype')
    op.drop_table('correctiveaction')
    # ### end Alembic commands ###
