"""Testing Stuff

Revision ID: 408aa52a25e8
Revises: cbe92a10882e
Create Date: 2022-08-19 12:14:40.604776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408aa52a25e8'
down_revision = 'cbe92a10882e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
