"""added mean_current field to measurement

Revision ID: 5b45775906f1
Revises: 3dcc7dc6ac0e
Create Date: 2022-08-23 16:45:51.531641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b45775906f1'
down_revision = '3dcc7dc6ac0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('mean_current', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'mean_current')
    # ### end Alembic commands ###
