"""testing

Revision ID: b44b542c3e7f
Revises: 128920805ec5
Create Date: 2022-08-25 15:49:55.313528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44b542c3e7f'
down_revision = '128920805ec5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
