"""Try

Revision ID: dd3fbd05a506
Revises: b44b542c3e7f
Create Date: 2022-08-25 17:04:40.760993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3fbd05a506'
down_revision = 'b44b542c3e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'failure', type_='foreignkey')
    op.drop_column('failure', 'failure_type')
    op.drop_column('failure', 'failure_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failure', sa.Column('failure_type_id', sa.INTEGER(), nullable=True))
    op.add_column('failure', sa.Column('failure_type', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'failure', 'failuretype', ['failure_type'], ['failuretype_id'])
    # ### end Alembic commands ###
