##################
# Style definitions
###################
font_headline = "Helvetiva 25"
font_normal = "Helvetica 15"
font_small = "Helvetica 13"



#################
# KEY DEFINITIONS
#################
# Layout keys
K_PAGE_1 = "-LAYOUT_PAGE_1-"
K_PAGE_2 = "-LAYOUT_PAGE_2-"
K_PAGE_3 = "-LAYOUT_PAGE_3-"

# Button keys
K_BTN_NAV_PREVIOUS_PAGE = "-K_BTN_NAV_PREVIOUS_PAGE-"
K_BTN_NAV_NEXT_PAGE = "-K_BTN_NAV_NEXT_PAGE-"

K_RADIO_BUTTON_80_CLICKED = "-FUNCTION_RADIO_BUTTON_80_CLICKED-"
K_RADIO_BUTTON_105_CLICKED = "-FUNCTION_RADIO_BUTTON_105_CLICKED-"
K_BTN_CONNECT_CAN = "-KEY_BUTTON_CONNECT_CAN-"
K_BTN_SOFTWARE_UPDATE = "-KEY_BUTTON_SOFTWARE_UPDATE-"

K_CHECKBOX_HAS_ENCODER = "-KEY_CHECKBOX_HAS_ENCODER-"
K_CHECKBOX_HAS_BRAKE = "-KEY_CHECKBOX_HAS_BRAKE-"

K_BTN_START_VELO_MODE = "-KEY_BUTTON_START_VELO_MODE-"
K_BTN_STOP_VELO_MODE = "-KEY_BUTTON_STOP_VELO_MODE-"


# Event key from threading (updates, finished etc.)
K_SOFTWARE_UPDATE_FEEDBACK = "-SOFTWARE_UPDATE_FEEDBACK-"
K_SOFTWARE_UPDATE_DONE = "-SOFTWARE_UPDATE_DONE-"
K_UPDATE_GRAPH = "-K_UPDATE_GRAPH-"


# Element keys (text, etc.)
K_TEXT_CAN_CONNECTED_STATUS = "-TEXT_CAN_CONNECTION_STATUS-"
K_PROGRESSBAR_SOFTWARE_UPDATE = "-PROGRESSBAR_SOFTWARE_UPDATE-"
K_TEXT_SOFTWARE_UPDATE_STATUS_TEXT = "-TEXT_SOFTWARE_UPDATE_STATUS_TEXT-"
K_CANVAS_GRAPH_PLOTTING = "-CANVAS_GRAPH_PLOTTING-"
