"""init

Revision ID: 04b315a0b264
Revises: 
Create Date: 2022-08-26 14:00:02.954164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b315a0b264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('improvement_successfull', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.Column('indicator_type', sa.Enum('overcurrent', 'calibration_both_tracks_values', 'not_measurable', name='indicatortype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('transmission_configuration', sa.Enum('config_80', 'config_80_encoder', 'config_105', 'config_105_break', 'config_105_encoder', 'config_105_break_encoder', name='transmissionconfiguration'), nullable=True),
    sa.Column('finished_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FailureImprovementTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('failureID', sa.Integer(), nullable=True),
    sa.Column('improvementID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failureID'], ['failure.id'], ),
    sa.ForeignKeyConstraint(['improvementID'], ['improvement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IndicatorFailureTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicatorID', sa.Integer(), nullable=True),
    sa.Column('failureID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failureID'], ['failure.id'], ),
    sa.ForeignKeyConstraint(['indicatorID'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('max_current', sa.Float(), nullable=True),
    sa.Column('min_current', sa.Float(), nullable=True),
    sa.Column('mean_current', sa.Float(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datapoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('measurement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datapoint')
    op.drop_table('measurement')
    op.drop_table('IndicatorFailureTable')
    op.drop_table('FailureImprovementTable')
    op.drop_table('failure')
    op.drop_table('assembly')
    op.drop_table('transmission')
    op.drop_table('indicator')
    op.drop_table('improvement')
    # ### end Alembic commands ###
