"""Testing Stuff

Revision ID: 0642337b7241
Revises: 408aa52a25e8
Create Date: 2022-08-19 12:25:39.143636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0642337b7241'
down_revision = '408aa52a25e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
