"""Testing stuff

Revision ID: 0826df7135af
Revises: 2fcd63a18356
Create Date: 2022-08-25 17:21:18.781483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0826df7135af'
down_revision = '2fcd63a18356'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
