"""Testing 

Revision ID: 0b1e1c58bfe4
Revises: 2239856f6d4a
Create Date: 2022-08-22 16:02:51.248439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1e1c58bfe4'
down_revision = '2239856f6d4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
