"""Simplifying

Revision ID: 37347a272d33
Revises: b267d9e6f9cc
Create Date: 2022-08-19 10:07:45.139787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37347a272d33'
down_revision = 'b267d9e6f9cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly',
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.transmission_id'], ),
    sa.PrimaryKeyConstraint('assembly_id')
    )
    op.create_table('measurement',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.assembly_id'], ),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.drop_table('assembly_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_step',
    sa.Column('assembly_step_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('assembly_step_order', sa.VARCHAR(length=6), nullable=True),
    sa.Column('transmission_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.transmission_id'], ),
    sa.PrimaryKeyConstraint('assembly_step_id')
    )
    op.drop_table('measurement')
    op.drop_table('assembly')
    # ### end Alembic commands ###
