"""init

Revision ID: 431cd881d2dd
Revises: 700faee06e3a
Create Date: 2022-09-10 14:05:24.265350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431cd881d2dd'
down_revision = '700faee06e3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failure', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('improvement', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('improvement', 'is_verified')
    op.drop_column('failure', 'is_verified')
    # ### end Alembic commands ###
