"""added created_at auto field

Revision ID: 44cc610aafff
Revises: 0642337b7241
Create Date: 2022-08-19 13:53:36.435969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cc610aafff'
down_revision = '0642337b7241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapoint', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('measurement', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'created_at')
    op.drop_column('datapoint', 'created_at')
    # ### end Alembic commands ###
