"""initial commit

Revision ID: 5fea246fc391
Revises: 
Create Date: 2022-08-26 10:14:15.355634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fea246fc391'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correctiveaction',
    sa.Column('corrective_action_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('corrective_action_id')
    )
    op.create_table('failuretype',
    sa.Column('failuretype_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('failure_classification', sa.Enum('overcurrent', 'calibration_both_tracks_have_values', 'not_measurable', name='failureclassification'), nullable=True),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.PrimaryKeyConstraint('failuretype_id')
    )
    op.create_table('transmission',
    sa.Column('transmission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('transmission_configuration', sa.Enum('config_80', 'config_80_encoder', 'config_105', 'config_105_break', 'config_105_encoder', 'config_105_break_encoder', name='transmissionconfiguration'), nullable=True),
    sa.Column('finished_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('transmission_id')
    )
    op.create_table('assembly',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.transmission_id'], ),
    sa.PrimaryKeyConstraint('assembly_id')
    )
    op.create_table('failure',
    sa.Column('failure_id', sa.Integer(), nullable=False),
    sa.Column('failure_type_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failuretype.failuretype_id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.transmission_id'], ),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_table('measurement',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('max_current', sa.Float(), nullable=True),
    sa.Column('min_current', sa.Float(), nullable=True),
    sa.Column('mean_current', sa.Float(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.assembly_id'], ),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_table('datapoint',
    sa.Column('datapoint_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('measurement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurement.measurement_id'], ),
    sa.PrimaryKeyConstraint('datapoint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datapoint')
    op.drop_table('measurement')
    op.drop_table('failure')
    op.drop_table('assembly')
    op.drop_table('transmission')
    op.drop_table('failuretype')
    op.drop_table('correctiveaction')
    # ### end Alembic commands ###
