"""added field cable_must_disconnected

Revision ID: 700faee06e3a
Revises: 0b49663c6de6
Create Date: 2022-09-09 11:51:39.344198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700faee06e3a'
down_revision = '0b49663c6de6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('improvement', sa.Column('cable_must_disconnected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('improvement', 'cable_must_disconnected')
    # ### end Alembic commands ###
