"""FailureType new field:'limit_overcurrent'

Revision ID: 8499a17c8191
Revises: 5b45775906f1
Create Date: 2022-08-25 14:55:40.166132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8499a17c8191'
down_revision = '5b45775906f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failuretype', sa.Column('limit_overcurrent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failuretype', 'limit_overcurrent')
    # ### end Alembic commands ###
