"""init

Revision ID: 8f7d1f49ddb5
Revises: 
Create Date: 2022-08-30 07:45:57.554939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7d1f49ddb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.Column('failure_type', sa.Enum('overcurrent', 'calibration_both_tracks_values', 'not_measurable', name='failuretype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('transmission_configuration', sa.Enum('config_80', 'config_80_encoder', 'config_105', 'config_105_break', 'config_105_encoder', 'config_105_break_encoder', name='transmissionconfiguration'), nullable=True),
    sa.Column('finished_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FailureImprovementTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('failureID', sa.Integer(), nullable=True),
    sa.Column('improvementID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failureID'], ['failure.id'], ),
    sa.ForeignKeyConstraint(['improvementID'], ['improvement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_step', sa.Enum('step_1_no_flexring', 'step_2_with_flexring', 'step_3_gearoutput_not_screwed', 'step_4_gearoutput_screwed', name='assemblystep'), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failureinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('failure_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failure_id'], ['failure.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvementinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('improvement_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['improvement_id'], ['improvement.id'], ),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('max_current', sa.Float(), nullable=True),
    sa.Column('min_current', sa.Float(), nullable=True),
    sa.Column('mean_current', sa.Float(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datapoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('measurement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datapoint')
    op.drop_table('measurement')
    op.drop_table('improvementinstance')
    op.drop_table('failureinstance')
    op.drop_table('assembly')
    op.drop_table('FailureImprovementTable')
    op.drop_table('transmission')
    op.drop_table('improvement')
    op.drop_table('failure')
    # ### end Alembic commands ###
