"""test

Revision ID: aed0d4505863
Revises: 3c5dc4b0972d
Create Date: 2022-08-22 12:47:30.128893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed0d4505863'
down_revision = '3c5dc4b0972d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
