"""my first migration2

Revision ID: b267d9e6f9cc
Revises: 00cd47aeb063
Create Date: 2022-08-19 09:19:59.083607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b267d9e6f9cc'
down_revision = '00cd47aeb063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
