"""Testing

Revision ID: cbe92a10882e
Revises: c3ad7a7510f5
Create Date: 2022-08-19 11:49:07.941989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe92a10882e'
down_revision = 'c3ad7a7510f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
