"""FailureType: deleted field:'limit_overcurrent'

Revision ID: d1556a538201
Revises: 8499a17c8191
Create Date: 2022-08-25 14:59:14.342798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1556a538201'
down_revision = '8499a17c8191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failuretype', 'limit_overcurrent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failuretype', sa.Column('limit_overcurrent', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
